<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGkmkw8x\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGkmkw8x/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerGkmkw8x.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerGkmkw8x\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerGkmkw8x\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Gkmkw8x',
    'container.build_id' => '330809f6',
    'container.build_time' => 1536355060,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerGkmkw8x');
