<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUgxuvdl\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUgxuvdl/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerUgxuvdl.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerUgxuvdl\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerUgxuvdl\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Ugxuvdl',
    'container.build_id' => 'f79543db',
    'container.build_time' => 1543367241,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerUgxuvdl');
